import assert from 'node:assert/strict';
import { writeFileSync } from 'node:fs';
import { after, before, test } from 'node:test';
import fixtures from '../../shared/fixtures/fixtures.v0.json' with { type: 'json' };
import { launchBrowser } from '../e2e/support.js';

// Phase 7 smoke test against a deployed Ruko (or the local container):
//   RUKO_URL=https://ruko.example npm run test:smoke
// Paths: online (server rules + templates or LLM), LLM off (template engine, same band), Bhashini off (TTS answers
// 503 browser_tts), airplane mode (the installed PWA checks on the phone). RUKO_EXPECT_LLM / RUKO_EXPECT_BHASHINI
// (on|off) make the mode an assertion; unset, the mode seen is only reported. RUKO_SMOKE_REPORT=<file> writes a
// Markdown record. Only fixture texts are sent, never real messages.

const BASE = (process.env.RUKO_URL ?? '').replace(/\/+$/, '');
const EXPECT_LLM = process.env.RUKO_EXPECT_LLM;
const EXPECT_BHASHINI = process.env.RUKO_EXPECT_BHASHINI;
const REPORT = process.env.RUKO_SMOKE_REPORT;
const WAKE_MS = Number(process.env.RUKO_WAKE_MS ?? 180_000);

const SCAM = fixtures.find((f) => f.id === 'sc-001');
const results = [];
let browser;

function step(name, fn) {
  test(name, async () => {
    try {
      const detail = await fn();
      results.push({ name, ok: true, detail: detail ?? '' });
    } catch (error) {
      results.push({ name, ok: false, detail: error.message.split('\n')[0] });
      throw error;
    }
  });
}

async function get(path, init) {
  return fetch(`${BASE}${path}`, { redirect: 'manual', ...init });
}

async function postJson(path, body) {
  return get(path, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
}

before(async () => {
  assert.ok(BASE, 'set RUKO_URL to the deployed origin, e.g. RUKO_URL=https://ruko-187c.onrender.com');
  // A free instance may be asleep: wait for readiness before timing anything.
  const deadline = Date.now() + WAKE_MS;
  for (;;) {
    try {
      if ((await get('/actuator/health/readiness')).status === 200) break;
    } catch { /* still waking */ }
    if (Date.now() > deadline) throw new Error(`${BASE} not ready within ${WAKE_MS / 1000} s`);
    await new Promise((resolve) => setTimeout(resolve, 3000));
  }
});

after(async () => {
  await browser?.close();
  if (!REPORT) return;
  const lines = [
    '# Smoke test', '',
    `Generated by \`RUKO_URL=… npm run test:smoke\` (\`pwa/smoke/live.test.js\`). Do not edit by hand.`, '',
    '| | |', '| --- | --- |',
    `| Target | ${BASE} |`,
    `| Run at | ${new Date().toISOString().replace('T', ' ').slice(0, 16)} UTC |`,
    `| Result | ${results.filter((r) => r.ok).length} / ${results.length} passed |`, '',
    '| Check | | Detail |', '| --- | --- | --- |',
    ...results.map((r) => `| ${r.name} | ${r.ok ? 'pass' : '**fail**'} | ${r.detail.replaceAll('|', '\\|')} |`), '',
  ];
  writeFileSync(REPORT, lines.join('\n'));
});

step('readiness: rules re-validated and three probes pass', async () => {
  const response = await get('/actuator/health/readiness');
  assert.equal(response.status, 200);
  assert.deepEqual(await response.json(), { status: 'UP' });
  return '/actuator/health/readiness UP';
});

step('one origin: the PWA shell, service worker, and manifest with headers', async () => {
  const shell = await get('/');
  assert.equal(shell.status, 200);
  assert.match(shell.headers.get('content-type'), /^text\/html/);
  assert.match(await shell.text(), /<div id="root">/);
  assert.equal(shell.headers.get('cache-control'), 'no-cache');
  assert.match(shell.headers.get('content-security-policy'), /connect-src 'self'/);
  assert.equal(shell.headers.get('x-content-type-options'), 'nosniff');
  assert.equal(shell.headers.get('referrer-policy'), 'no-referrer');
  assert.match(shell.headers.get('permissions-policy'), /microphone=\(self\)/);

  const share = await get('/share?text=smoke');
  assert.equal(share.status, 200, 'the share target is an app route');
  assert.equal((await get('/sw.js')).status, 200);
  const manifest = await (await get('/manifest.webmanifest')).json();
  assert.equal(manifest.share_target.action, '/share');
  return 'shell, /share, /sw.js, manifest share_target';
});

let engine;
step('online: a scam fixture comes back high_concern, decided by the rules', async () => {
  const started = Date.now();
  const response = await postJson('/api/v1/analyze', { text: SCAM.text, lang: SCAM.lang, source: SCAM.source });
  const took = Date.now() - started;
  assert.equal(response.status, 200);
  const result = await response.json();
  assert.equal(result.band, SCAM.expected.band);
  assert.equal(result.content_class, SCAM.expected.content_class);
  assert.ok(['template', 'llm'].includes(result.engine), `engine ${result.engine}`);
  engine = result.engine;
  return `band ${result.band}, engine ${result.engine}, ${took} ms`;
});

step('LLM mode: the template engine answers when the LLM is off or unavailable', async () => {
  assert.ok(engine, 'online check ran');
  if (EXPECT_LLM === 'off') assert.equal(engine, 'template', 'LLM expected off');
  if (EXPECT_LLM === 'on') assert.equal(engine, 'llm', 'LLM expected on');
  // Rules decide the band either way, so every labelled scam band matches with or without the model.
  for (const id of ['sc-002', 'sc-008', 'ed-002']) {
    const fixture = fixtures.find((f) => f.id === id);
    const result = await (await postJson('/api/v1/analyze', { text: fixture.text, lang: fixture.lang, source: fixture.source })).json();
    assert.equal(result.band, fixture.expected.band, id);
  }
  return engine === 'template' ? 'LLM off: template engine, bands as labelled' : 'LLM on: bands still as labelled';
});

step('Bhashini mode: TTS is audio, or 503 telling the phone to speak it itself', async () => {
  const response = await postJson('/api/v1/voice/tts',
    { script_key: 'sig.C2.spoken', lang: 'hi', counts: { red_flags: 1, couldnt_verify: 0, reassuring: 0 } });
  if (response.status === 200) {
    assert.match(response.headers.get('content-type'), /^audio\//);
    if (EXPECT_BHASHINI === 'off') assert.fail('Bhashini expected off');
    return 'Bhashini on: audio';
  }
  assert.equal(response.status, 503);
  assert.equal((await response.json()).fallback, 'browser_tts');
  if (EXPECT_BHASHINI === 'on') assert.fail('Bhashini expected on');
  return 'Bhashini off: 503 browser_tts';
});

step('content, docs, and no journal route', async () => {
  for (const path of ['/api/v1/content/how-ruko-decides?lang=hi', '/api/v1/content/recovery?lang=en', '/api/v1/content/links?lang=en']) {
    assert.equal((await get(path)).status, 200, path);
  }
  const docs = await (await get('/v3/api-docs')).json();
  assert.equal(Object.keys(docs.paths).length, 7);
  assert.equal((await get('/swagger-ui/index.html')).status, 200);
  for (const path of ['/api/v1/journal', '/api/v1/journal/entries']) {
    const response = await get(path);
    assert.equal(response.status, 404, path);
    assert.match(response.headers.get('content-type'), /^application\/problem\+json/);
  }
  return 'content 200, OpenAPI 7 paths, journal 404';
});

step('browser online, then airplane mode: the installed PWA checks on the phone', async () => {
  browser = await launchBrowser();
  const context = await browser.newContext({ serviceWorkers: 'allow' });
  const page = await context.newPage();
  const errors = [];
  page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()); });

  await page.goto(BASE);
  await page.evaluate(() => navigator.serviceWorker.ready);
  await page.reload();
  assert.ok(await page.evaluate(() => Boolean(navigator.serviceWorker.controller)), 'service worker controls the page');

  const analyzed = page.waitForResponse((r) => r.url().endsWith('/api/v1/analyze'));
  await page.locator('textarea').fill(SCAM.text);
  await page.getByRole('button', { name: 'जाँचें', exact: true }).click();
  assert.equal((await analyzed).status(), 200);
  await page.waitForURL('**/result');
  assert.equal(await page.locator('.notice', { hasText: 'इसी फ़ोन पर' }).count(), 0, 'online result came from the server');

  await context.setOffline(true);
  await page.goto(BASE);
  await page.locator('textarea').fill(SCAM.text);
  await page.getByRole('button', { name: 'जाँचें', exact: true }).click();
  await page.waitForURL('**/result');
  await page.locator('.notice', { hasText: 'इसी फ़ोन पर' }).waitFor();
  assert.equal(await page.evaluate(() => localStorage.getItem('ruko.on_device_total')), '1');
  assert.deepEqual(errors.filter((e) => /Content Security Policy/i.test(e)), [], 'no CSP violations');
  await context.close();
  return 'online result from server; offline result on device (ruko.on_device_total = 1)';
});
