import assert from 'node:assert/strict';
import { writeFileSync } from 'node:fs';
import { after, before, test } from 'node:test';
import fixtures from '../../shared/fixtures/fixtures.v0.json' with { type: 'json' };
import { launchBrowser, serveBuild } from '../e2e/support.js';
import { analyzeInNode } from '../scripts/node-engine.mjs';

// Text path on an emulated low-end phone (plan Phase 6: p95 at most 8 s on throttled 3G). Chrome's own "Slow 3G"
// profile (2 s round trip, 400 kbit/s each way) and a 4x slower CPU. The local server answers /analyze with the
// on-device engine, whose output the parity tests keep identical to the server's; server time itself is in
// docs/eval-report.md. Writes docs/eval-text-path.md. Needs a production build: npm run build && npm run test:perf.

const RUNS = 5;
const TARGET_MS = 8000;
const SLOW_3G = { offline: false, latency: 2000, downloadThroughput: (500 * 1000) / 8 * 0.8, uploadThroughput: (500 * 1000) / 8 * 0.8 };
const CPU_SLOWDOWN = 4;
const REPORT = new URL('../../docs/eval-text-path.md', import.meta.url);
const MESSAGE = fixtures.find((fixture) => fixture.id === 'sc-002');

let server;
let browser;

before(async () => {
  server = await serveBuild({
    api: (request, body) => {
      if (request.method !== 'POST' || !request.url.startsWith('/api/v1/analyze')) return null;
      const { text, lang, source, ocr_confidence: ocrConfidence } = JSON.parse(body);
      return { status: 200, json: { ...analyzeInNode({ text, lang, source, ocrConfidence: ocrConfidence ?? null }), engine: 'template' } };
    },
  });
  browser = await launchBrowser();
});

after(async () => {
  await browser?.close();
  await server?.close();
});

async function throttled(context) {
  const page = await context.newPage();
  const cdp = await context.newCDPSession(page);
  await cdp.send('Network.enable');
  await cdp.send('Network.emulateNetworkConditions', SLOW_3G);
  await cdp.send('Emulation.setCPUThrottlingRate', { rate: CPU_SLOWDOWN });
  return page;
}

/** Open the app, paste the message, tap check, wait for the band. Returns [open to result, tap to result] in ms. */
async function textPath(page) {
  const opened = Date.now();
  await page.goto(`${server.origin}/`, { waitUntil: 'commit' });
  await page.locator('textarea').fill(MESSAGE.text);
  const tapped = Date.now();
  await page.getByRole('button', { name: 'जाँचें', exact: true }).click();
  await page.locator('.band-label').waitFor({ timeout: 60_000 });
  const done = Date.now();
  return [done - opened, done - tapped];
}

const p95 = (values) => [...values].sort((a, b) => a - b)[Math.ceil(0.95 * values.length) - 1];
const median = (values) => [...values].sort((a, b) => a - b)[Math.floor(values.length / 2)];
const seconds = (ms) => `${(ms / 1000).toFixed(1)} s`;

test('text path on slow 3G with a slow CPU', { timeout: 600_000 }, async () => {
  const cold = [];
  const warm = [];
  for (let run = 0; run < RUNS; run++) {
    const context = await browser.newContext({ serviceWorkers: 'allow' });
    const first = await throttled(context);
    cold.push(await textPath(first));
    await first.evaluate(() => navigator.serviceWorker.ready);
    await first.close();
    warm.push(await textPath(await throttled(context)));
    await context.close();
  }

  const rows = [
    ['First visit (nothing cached): open, paste, check', cold.map((r) => r[0])],
    ['Installed (shell from the service worker): open, paste, check', warm.map((r) => r[0])],
    ['Tap "check" to result shown', [...cold, ...warm].map((r) => r[1])],
  ];
  const lines = [
    '# Text path on an emulated low-end phone',
    '',
    'Generated by `cd pwa && npm run build && npm run test:perf` (`perf/text-path.test.js`). Do not edit by hand.',
    '',
    `Production build in headless ${process.env.PW_CHANNEL ?? (process.platform === 'win32' ? 'Edge' : 'Chrome')} with Chrome's "Slow 3G" profile (2 s round trip, 400 kbit/s each way) and the CPU slowed ${CPU_SLOWDOWN}×. ` +
      `${RUNS} runs each, message \`${MESSAGE.id}\`. The local server answers \`/analyze\` with the on-device engine (identical output to the server, see the parity tests); ` +
      'add the server p95 from [eval-report.md](./eval-report.md) for a real deployment. A real low-end Android phone on a real 3G connection is still the final check.',
    '',
    '| Path | Median | p95 | Target p95 | |',
    '| --- | --- | --- | --- | --- |',
    ...rows.map(([name, values]) => `| ${name} | ${seconds(median(values))} | ${seconds(p95(values))} | ≤ 8 s | ` +
      `${p95(values) <= TARGET_MS ? 'met' : '**not met**'} |`),
    '',
    'A first visit downloads the shell over the 2 s round-trip link before the check can start; once the PWA is ' +
      'installed, only the check itself uses the network.',
    '',
  ];
  writeFileSync(REPORT, lines.join('\n'), 'utf8');
  console.log(lines.join('\n'));

  assert.ok(p95(warm.map((r) => r[0])) <= TARGET_MS, 'installed text path p95 within 8 s');
});
