// Scores the behaviour study sheet (docs/study/README.md). Usage:
//   node scripts/score-study.mjs docs/study/results.csv            prints the summary
//   node scripts/score-study.mjs docs/study/results.csv --write    also writes docs/study/results.md
// The sheet holds coded answers only: participant codes, never names, and no free text.
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import fixtures from '../shared/fixtures/fixtures.v0.json' with { type: 'json' };

export const COLUMNS = ['participant', 'group', 'message_id', 'condition', 'answer', 'restated'];
export const SET_A = ['sc-001', 'sc-005', 'sc-020', 'ed-005', 'ed-012'];
export const SET_B = ['sc-002', 'sc-017', 'sc-033', 'ed-008', 'ed-003'];
const KEY = Object.fromEntries(fixtures.filter((f) => [...SET_A, ...SET_B].includes(f.id))
  .map((f) => [f.id, f.kind === 'scam' ? 'risky' : 'fine']));
const IMPROVEMENT_TARGET = 30;
const RESTATE_TARGET = 80;

/** Parses and checks the sheet; throws with the line number on anything unexpected. */
export function parseSheet(csv) {
  const lines = csv.replace(/^\uFEFF/, '').split(/\r?\n/).filter((line) => line.trim() !== '');
  if (lines.length === 0 || lines[0].split(',').map((s) => s.trim()).join(',') !== COLUMNS.join(',')) {
    throw new Error(`the first line must be: ${COLUMNS.join(',')}`);
  }
  const rows = lines.slice(1).map((line, i) => {
    const cells = line.split(',').map((s) => s.trim());
    const where = `line ${i + 2}`;
    if (cells.length !== COLUMNS.length) throw new Error(`${where}: expected ${COLUMNS.length} columns`);
    const row = Object.fromEntries(COLUMNS.map((column, c) => [column, cells[c]]));
    if (!/^P[0-9]{2}$/.test(row.participant)) throw new Error(`${where}: participant must be a code like P01`);
    if (!['A', 'B'].includes(row.group)) throw new Error(`${where}: group must be A or B`);
    if (!(row.message_id in KEY)) throw new Error(`${where}: unknown message ${row.message_id}`);
    if (!['without', 'with'].includes(row.condition)) throw new Error(`${where}: condition must be without or with`);
    const withoutSet = row.group === 'A' ? SET_A : SET_B;
    if ((row.condition === 'without') !== withoutSet.includes(row.message_id)) {
      throw new Error(`${where}: group ${row.group} sees ${row.message_id} ${withoutSet.includes(row.message_id) ? 'without' : 'with'} Ruko`);
    }
    if (!['risky', 'fine', 'unsure'].includes(row.answer)) throw new Error(`${where}: answer must be risky, fine, or unsure`);
    if (row.condition === 'with' ? !['yes', 'no'].includes(row.restated) : row.restated !== '') {
      throw new Error(`${where}: restated is yes or no with Ruko, and empty without`);
    }
    return row;
  });
  const seen = new Set();
  for (const row of rows) {
    const id = `${row.participant}/${row.message_id}`;
    if (seen.has(id)) throw new Error(`${id} appears twice`);
    seen.add(id);
  }
  return rows;
}

const pct = (a, b) => (b === 0 ? 0 : (100 * a) / b);

/** The two plan metrics, from complete participants only (all 10 messages answered). */
export function score(rows) {
  const byParticipant = Map.groupBy(rows, (row) => row.participant);
  const complete = [...byParticipant.values()].filter((answers) => answers.length === SET_A.length + SET_B.length);
  const used = complete.flat();
  const correct = (condition) => used.filter((r) => r.condition === condition && r.answer === KEY[r.message_id]).length;
  const total = (condition) => used.filter((r) => r.condition === condition).length;
  const withRuko = used.filter((r) => r.condition === 'with');
  const without = pct(correct('without'), total('without'));
  const withR = pct(correct('with'), total('with'));
  const restated = pct(withRuko.filter((r) => r.restated === 'yes').length, withRuko.length);
  return {
    n: complete.length,
    incomplete: byParticipant.size - complete.length,
    groups: { A: complete.filter((a) => a[0].group === 'A').length, B: complete.filter((a) => a[0].group === 'B').length },
    without, with: withR, improvement: withR - without, restated,
    improvementMet: withR - without >= IMPROVEMENT_TARGET,
    restatedMet: restated >= RESTATE_TARGET,
  };
}

export function summary(result) {
  const f = (value) => `${value.toFixed(1)}%`;
  return [
    '# Behaviour study results',
    '',
    'Generated by `node scripts/score-study.mjs docs/study/results.csv --write`. Do not edit by hand.',
    '',
    `Participants: **n = ${result.n}** (group A ${result.groups.A}, group B ${result.groups.B})` +
      (result.incomplete ? `; ${result.incomplete} incomplete sheet(s) left out` : '') + '.',
    '',
    '| Measure | Result | Target | |',
    '| --- | --- | --- | --- |',
    `| Correctly identified, without Ruko | ${f(result.without)} | | |`,
    `| Correctly identified, with Ruko | ${f(result.with)} | | |`,
    `| Improvement | ${result.improvement >= 0 ? '+' : ''}${result.improvement.toFixed(1)} pp | +30 pp | ${result.improvementMet ? 'met' : '**not met**'} |`,
    `| Could restate the main reason (with Ruko) | ${f(result.restated)} | ≥ 80% | ${result.restatedMet ? 'met' : '**not met**'} |`,
    '',
    'A small convenience sample; read as an indication, not a statistical result.',
    '',
  ].join('\n');
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const [file, flag] = process.argv.slice(2);
  if (!file) {
    console.error('usage: node scripts/score-study.mjs <results.csv> [--write]');
    process.exit(2);
  }
  const text = summary(score(parseSheet(readFileSync(file, 'utf8'))));
  console.log(text);
  if (flag === '--write') writeFileSync(new URL('../docs/study/results.md', import.meta.url), text, 'utf8');
}
