package in.ruko.guardrail;

import static org.assertj.core.api.Assertions.assertThat;

import in.ruko.api.dto.AnalyzeRequest;
import in.ruko.api.dto.AnalyzeResponse;
import in.ruko.pipeline.Lang;
import in.ruko.snapshot.SebiSnapshotIndex;
import in.ruko.support.Pipeline;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

/**
 * Submission pack: the guardrail linter report, from the same cases as {@link LinterTest}. Only runs with
 * {@code ./mvnw -Psubmission test}; writes {@code docs/submission/linter-report.md}, then asserts the gate.
 */
@Tag("submission")
class LinterReportTest {

    private static final Path REPORT = Path.of("..", "docs", "submission", "linter-report.md");

    private static final Map<LintCode, String> BLOCKS = new EnumMap<>(Map.of(
            LintCode.L1, "Recommendation language: buy, sell, hold, invest now (English, Hindi, Hinglish)",
            LintCode.L2, "Ticker symbols and company names from the dated NSE/BSE list",
            LintCode.L3, "Verdict words (safe, scam, fraud, genuine, verified) outside the fixed footer",
            LintCode.L4, "Cards over 25 words, analogies over 40, blank cards, evidence not quoted from the input",
            LintCode.L5, "Links off the allowlist, phone numbers other than 1930, HTML or Markdown",
            LintCode.L6, "Output in a language other than the one asked for",
            LintCode.L7, "Price targets and return predictions outside a verbatim quote",
            LintCode.L8, "Band, content class, analogy, or signal ids that differ from the rule result"));

    private record BadCard(LintCode code, Lang lang, String card, boolean caught) {
    }

    @Test
    void writeReport() throws Exception {
        int templates = 0;
        int clean = 0;
        Map<String, Integer> templateCodes = new TreeMap<>();
        for (var arguments : LinterTest.templateOutputs().toList()) {
            Object[] a = arguments.get();
            Pipeline.Fixture fixture = (Pipeline.Fixture) a[1];
            Pipeline.Drafted drafted = Pipeline.drafted(new AnalyzeRequest(fixture.text(), (Lang) a[2], fixture.source(),
                    fixture.ocrConfidence()), (SebiSnapshotIndex) a[3]);
            LintResult result = Pipeline.LINTER.lint(drafted.response(), drafted.context());
            templates++;
            if (result.violations().isEmpty()) {
                clean++;
            }
            result.codes().forEach(code -> templateCodes.merge(code.name(), 1, Integer::sum));
        }

        int fallbacks = 0;
        int cleanFallbacks = 0;
        for (Lang lang : Lang.values()) {
            Pipeline.Drafted drafted = LinterTest.scam(lang);
            AnalyzeResponse r = drafted.response();
            fallbacks++;
            if (Pipeline.LINTER.lint(FallbackTemplates.generic(lang, r.entities(), r.band(), r.contentClass(), r.counts()),
                    drafted.context()).violations().isEmpty()) {
                cleanFallbacks++;
            }
        }

        List<BadCard> bad = new ArrayList<>();
        for (var arguments : LinterTest.badCards().toList()) {
            Object[] a = arguments.get();
            LintCode code = (LintCode) a[0];
            Lang lang = (Lang) a[1];
            String card = (String) a[2];
            Pipeline.Drafted drafted = LinterTest.scam(lang);
            LintResult result = Pipeline.LINTER.lint(LinterTest.withCard(drafted.response(), card), drafted.context());
            bad.add(new BadCard(code, lang, card, result.codes().contains(code)));
        }
        long caught = bad.stream().filter(BadCard::caught).count();

        StringBuilder md = new StringBuilder();
        md.append("# Guardrail linter report\n\n")
                .append("Generated by `cd server && ./mvnw -Psubmission test` (`LinterReportTest`, same cases as ")
                .append("`LinterTest`, which gates CI). Do not edit by hand.\n\n")
                .append("| | |\n| --- | --- |\n")
                .append("| Generated | ").append(ZonedDateTime.now(ZoneId.of("Asia/Kolkata"))
                        .format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm z"))).append(" |\n")
                .append("| Linter | `GuardrailLinter`, 8 checks (L1 to L8), run on every response before it leaves the server |\n")
                .append("| Fails closed | composed draft, else the pure template draft, else a static pre-approved response |\n\n")
                .append("## Summary\n\n| Measure | Result | Target | |\n| --- | --- | --- | --- |\n")
                .append("| Template outputs with zero violations (each fixture × hi/en × shipped/dated snapshot) | ")
                .append(count(clean, templates)).append(" | 100% | ").append(met(clean == templates)).append(" |\n")
                .append("| Static fallback response with zero violations (hi/en) | ")
                .append(count(cleanFallbacks, fallbacks)).append(" | 100% | ").append(met(cleanFallbacks == fallbacks)).append(" |\n")
                .append("| Hand-written bad cards caught by the check they target | ")
                .append(count((int) caught, bad.size())).append(" | 100% | ").append(met(caught == bad.size())).append(" |\n\n");
        if (!templateCodes.isEmpty()) {
            md.append("Template violations by code: ").append(templateCodes).append("\n\n");
        }

        md.append("## Checks\n\n| Code | Blocks | Bad cards caught | Example it caught |\n| --- | --- | --- | --- |\n");
        for (LintCode code : LintCode.values()) {
            List<BadCard> forCode = bad.stream().filter(card -> card.code() == code).toList();
            String example = forCode.stream().filter(BadCard::caught).map(card -> card.lang().wire() + ": " + card.card())
                    .findFirst().orElse(code == LintCode.L8 ? "rule-result fields, see `LinterTest.draftMustSayWhatTheRulesSaid`" : "");
            md.append("| ").append(code).append(" | ").append(BLOCKS.get(code)).append(" | ")
                    .append(forCode.isEmpty() ? "field cases (CI)" : count((int) forCode.stream().filter(BadCard::caught).count(), forCode.size()))
                    .append(" | ").append(cell(example)).append(" |\n");
        }
        md.append("\nAllowed on purpose, and tested: a quote copied verbatim from the message (L7 exempts it), links to ")
                .append("`siportal.sebi.gov.in` and `tel:1930` (L5), the fixed \"no flags is not safe\" footer (L3), and ")
                .append("dropping the analogy (L8).\n\n")
                .append("In the running server every failed check increments `ruko_lint_fail_total{code}`. ")
                .append("Serving all 80 fixtures leaves it at 0; see [eval-report.md](../eval-report.md#guardrail-linter).\n");

        Files.createDirectories(REPORT.getParent());
        Files.writeString(REPORT, md.toString(), StandardCharsets.UTF_8);

        assertThat(clean).as("clean template outputs").isEqualTo(templates);
        assertThat(cleanFallbacks).as("clean fallbacks").isEqualTo(fallbacks);
        assertThat(caught).as("bad cards caught").isEqualTo(bad.size());
    }

    private static String count(int part, int total) {
        return String.format("%d / %d (%.1f%%)", part, total, total == 0 ? 0 : 100.0 * part / total);
    }

    private static String met(boolean met) {
        return met ? "met" : "**not met**";
    }

    private static String cell(String text) {
        return text.replace("|", "\\|").replace("\n", " ");
    }
}
